### ISSUE TITLE
deosent work on replit

### ISSUE THREAD

**Issue by deinemuttermitbutter** [Sobhan-SRZA/Nitro-Generator-Bot#16]
is keep saying in the console:

 python3 main.py
 * Serving Flask app ''
 * Debug mode: off
2023-03-24 16:22:57 INFO     discord.client logging in using static token
have an error.

**Comment by Sobhan-SRZA** [comment]
Hi there, your bot token is invalid or you need to enable all intents of bot on discord developer portal. Like on the image.
![Image](https://user-images.githubusercontent.com/90289153/227698260-f5c584b9-365d-4777-8f11-c7042749da86.png)

**Comment by deinemuttermitbutter** [comment]
still doesn´t work. same error :( 

i provided an VALID token, i cecked it with another simple script to log into the bot token .... 
my script to log into the token:
import os
import discord

intents = discord.Intents.default()
client = discord.Client(intents=intents)

@client.event
async def on_ready():
    print('Logged in as {0.user}'.format(client))

client.run('DISCORD_TOKEN')

but the same token doesnt work for the nitro generator bot.
anything else i need to maybe configure to run the bot? only the example.env file?

**Comment by deinemuttermitbutter** [comment]
solution found: 
![Screenshot (471)](https://user-images.githubusercontent.com/126014902/227724230-b72f60dc-da53-43f6-a9dc-a327d674de49.jpg)

just replace "token" in line 146 with your actual token.

**Comment by Sobhan-SRZA** [comment]
> solution found: ![Screenshot (472)](https://user-images.githubusercontent.com/126014902/227724420-47c4e4f9-4ad3-4087-b0a0-12e48a5d6d78.jpg)
> 
> just replace "token" in line 146 with your actual token.

That’s fine, but I set bot token on .env file and env file at replit is in secret option. you have to set token on there.
![1BA7F0EE-272E-49DC-8369-CD1EBA8A740C](https://user-images.githubusercontent.com/90289153/227725308-85fff211-31d6-40c6-a7c4-952676e36d2f.jpeg)

**Comment by Sobhan-SRZA** [comment]
> still doesn´t work. same error :(
> 
> i provided an VALID token, i cecked it with another simple script to log into the bot token .... my script to log into the token: import os import discord
> 
> intents = discord.Intents.default() client = discord.Client(intents=intents)
> 
> @client.event async def on_ready(): print('Logged in as {0.user}'.format(client))
> 
> client.run('DISCORD_TOKEN')
> 
> but the same token doesnt work for the nitro generator bot. anything else i need to maybe configure to run the bot? only the example.env file?

you place your bot in wrong place. place it on .env file.
