### ISSUE TITLE
Fix this messy s**t! MY EYES ARE LITERALLY BLEEDING

### ISSUE THREAD

**Issue by Heisenberg-tr** [Sobhan-SRZA/Nitro-Generator-Bot#17]
I literally wasted my 10 mins of my life with debugging your buggy and messy code to find out the scam.

What's wrong with you? Are you drunk while writing this s**t or something? ARE YOU AUTISTIC??

Learn the shit you don't know properly in its school.

**Comment by Sobhan-SRZA** [comment]
Hi, What is the matter?

**Comment by shervinbdndev** [comment]
> I literally wasted my 10 mins of my life with debugging your buggy and messy code to find out the scam.
> 
> What's wrong with you? Are you drunk while writing this s**t or something? ARE YOU AUTISTIC??
> 
> Learn the shit you don't know properly in its school.

chill bro
what just happened?

**Comment by Sobhan-SRZA** [comment]
1- `.env` Is safe and secret file.
2- I fix it.
3- Not in all times.
4- Maybe someone use the bot on public server and need withe list channel on his guild.
5- You can setup it easily why you doing this?
6- I don’t know what are you talking about.

**Comment by Heisenberg-tr** [comment]
1 - Env is not safe and secret file ITS LITERALLY PLAIN TEXT WTF

2 - Finally

3 - You are a liar and dirty coder its just genersitng random strings you are just lying yo people it doesnt even generate a valid used link

4 - Who tf will break the Discord T.O.S in public server? 

5 - When i runned the bot for first time the bot deosnt worked then i looked the code and see the channel whitelist why you did not take it from a txt file?

6 - I mean avatar function and help function is unnecessary

**Comment by Sobhan-SRZA** [comment]
1- I don’t think so.
3- OK I’m liar.
4- I know that guy. I see so many guilds do this(public)
 5- If you don’t like code why are use it?
6- This isn’t perfect bot. This is simple bot for example.

**Comment by shervinbdndev** [comment]
> 1 - Env is not safe and secret file ITS LITERALLY PLAIN TEXT WTF
> 
> 2 - Finally
> 
> 3 - You are a liar and dirty coder its just genersitng random strings you are just lying yo people it doesnt even generate a valid used link
> 
> 4 - Who tf will break the Discord T.O.S in public server? 
> 
> 5 - When i runned the bot for first time the bot deosnt worked then i looked the code and see the channel whitelist why you did not take it from a txt file?
> 
> 6 - I mean avatar function and help function is unnecessary
> 
> 

you can fork this project and replace your settings brother
this place is not for argument
and one last thing
if you have any problem with this code,
you're free to create your script yourself instead of using others script

**Comment by Sobhan-SRZA** [comment]
> 

OK You are great programer. Bye Bye
