### ISSUE TITLE
Bot problem

### ISSUE THREAD

**Issue by kreisler0** [Sobhan-SRZA/Nitro-Generator-Bot#18]
Bot will not answer my command
<img width="273" alt="image" src="https://github.com/Sobhan-SRZA/Nitro-Generator-Bot/assets/136276036/f5177cbb-fd38-40ac-8ff1-d778a6cb7b78">

**Comment by Sobhan-SRZA** [comment]
Hello
Sorry that's my bad :(
Add whitelist text channel id on source code at line 30 in "main.py" file.
Again sorry

**Comment by kreisler0** [comment]
All g overall the code looks great from analysing!
Good job

**Comment by Sobhan-SRZA** [comment]
> All g overall the code looks great from analysing! Good job

Very thanks ❤️
