### ISSUE TITLE
The bot token thing still not working

### ISSUE THREAD

**Issue by kreisler0** [Sobhan-SRZA/Nitro-Generator-Bot#20]
<img width="290" alt="image" src="https://github.com/Sobhan-SRZA/Nitro-Generator-Bot/assets/136276036/862f1ced-8b8b-45cb-9a95-026c972e5332">
Changed the thing already but uhh, doesn't work. Maybe do it in python like #replace xxx with ur channel id instead of routing it to configs.json? Idk I ain't an expert in this.

**Comment by Sobhan-SRZA** [comment]
oh
Please send image about your code or send code here

**Comment by kreisler0** [comment]
Here is config:
{
  "token": "place_your_bot_token_here",
  "prefix": "place_your_bot_prefix_here",
  "valid_channels": [
    1055708169587933196
  ]
}
Here is main.py:
[Main.txt](https://github.com/Sobhan-SRZA/Nitro-Generator-Bot/files/11755475/Main.txt)
Here is error that comes up when run also:
[Error.txt](https://github.com/Sobhan-SRZA/Nitro-Generator-Bot/files/11755490/Error.txt)

**Comment by Sobhan-SRZA** [comment]
Did you place channel id?

**Comment by kreisler0** [comment]
yeah see i put the channel id in the given space (starting with 10)

**Comment by Sobhan-SRZA** [comment]
I mean maybe it is server id or message id and not channel id
