### ISSUE TITLE
What the hell did I just witness

### ISSUE THREAD

**Issue by kristiankunc** [Sobhan-SRZA/Nitro-Generator-Bot#25]
Try to install dependencies, doesnt matter if it fails.
Try to install dependencies again, if it fails, install dependencies again.
I think you took "Third time pays for all" way too seriously.

```py
try: os.system("pip install -r ./requirements.txt")
except: pass
try: os.system("py -m pip install -r ./requirements.txt")
except: os.system("python -m pip install -r ./requirements.txt")
```
Is this the way to install dependencies nowdays?
Damn must've forgot to update to python 3.11.69 surely
Once Tim Peters dies he will surely be rolling over in his grave because of these nitro generator ahh inovationns

**Comment by Sobhan-SRZA** [comment]
You right that’s my bad🫠
sorry

tell me how can write better one

**Comment by kristiankunc** [comment]
It is a common practice to include the dependency installation instructions in the README instead of putting them directly i to your code as currently, it would be ran every time you start the script. I'd suggest just removing it and putting and write the instructions manually

**Comment by Sobhan-SRZA** [comment]
thank you🙏🏻 
I will do it
